<?php

namespace Database\Seeders;

use App\Models\Skill;
use Illuminate\Database\Seeder;

class SkillSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $skills = [
            [
                'title' => 'Creativity',
                'slug' => 'creativity',
                'description' => 'Creativity is defined as the tendency to
                generate or recognize ideas, alternatives, or possibilities
                that may be useful in solving problems, communicating with others,
                 and entertaining ourselves and others.',
            ],
            [
                'title' => 'Interpersonal Skills',
                'slug' => 'interpersonal-skills',
                'description' => 'Interpersonal skills are the behaviors and tactics a
                person uses to interact with others effectively.
                 In the business world, the term refers to an employees
                  ability to work well with others.
                  Interpersonal skills range from communication and
                  listening to attitude and deportment',
            ],
            [
                'title' => 'Critical Thinking',
                'slug' => 'critical-thinking',
                'description' => 'Critical thinking is the intellectually disciplined
                process of actively and skillfully conceptualizing, applying, analyzing,
                 synthesizing, and/or evaluating information gathered from, or generated by,
                  observation, experience, reflection, reasoning, or communication,
                  as a guide to belief and action',
            ],
            [
                'title' => 'Problem Solving',
                'slug' => 'problem-solving',
                'description' => 'Problem solving is the act of defining a problem;
                 determining the cause of the problem;
                identifying, prioritizing, and selecting alternatives for a solution',
            ],
            [
                'title' => 'Public Speaking',
                'slug' => 'public-speaking',
                'description' => 'the art of effective oral communication with an audience.
                 Synonyms Example Sentences Learn More About public speaking.',
            ],
            [
                'title' => 'Customer Service Skills',
                'slug' => 'customer-service-skills',
                'description' => 'Customer service skills include the ability to make
                a good impression with customers. ... They must be courteous to customers,
                 handle their questions and issues in an easy-going manner and demonstrate a
                  keen knowledge of the companys products and services.',
            ],
            [
                'title' => 'Teamwork Skills',
                'slug' => 'teamwork-skills',
                'description' => 'Teamwork skills are the qualities and
                abilities that allow you to work well with others during conversations,
                projects, meetings or other collaborations. Having teamwork skills is dependent
                 on your ability to communicate well,
                 actively listen and be responsible and honest',
            ],
            [
                'title' => 'Communication',
                'slug' => 'communication',
                'description' => 'Communication is simply the act of transferring information
                from one place, person or group to another. Every communication involves (at least)
                one sender, a message and a recipient. ... The transmission of
                the message from sender to recipient can be affected by a huge range of things',
            ],
            [
                'title' => 'Collaboration',
                'slug' => 'collaboration',
                'description' => 'Collaboration is a working practice whereby individuals
                work together for a common purpose to achieve business benefit.
                 Collaboration enables individuals
                 to work together to achieve a defined and common business purpose.',
            ],
            [
                'title' => 'Accounting',
                'slug' => 'accounting',
                'description' => 'Accounting is the process of recording financial transactions
                pertaining to a business. ... The financial statements used in accounting are a
                concise summary of financial transactions over an accounting period,
                 summarizing a companys operations, financial position and cash flows.',
            ],

        ];

        foreach($skills as $skill) {
            Skill::create($skill);
        }
    }
}
